nimble/host: Fix not catching conversion error in hex2bin
hex2val returns BLE_HS_EINVAL on error which is positive value.
This could result in UUID conversion errors as hex2bin is used
by ble_uuid_from_str.

This was also causing build error with GCC 9:

repos/apache-mynewt-nimble/nimble/host/src/ble_uuid.c:76:28: error:
     'tmp_val' may be used uninitialized in this function
     [-Werror=maybe-uninitialized]
   76 |         bin[len] = tmp_val << 4;
      |                    ~~~~~~~~^~~~
cc1: all warnings being treated as errors