oic/ble_adapter: Fix build errors build for oc_client configuration
Error: repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:
In function 'oc_send_buffer_gatt':
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:380:14:
error: unused variable 'attr_handle' [-Werror=unused-variable]
     uint16_t attr_handle;
              ^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:379:14:
error: variable 'conn_handle' set but not used
[-Werror=unused-but-set-variable]
     uint16_t conn_handle;
              ^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:378:14:
error: unused variable 'mtu' [-Werror=unused-variable]
     uint16_t mtu;
              ^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:377:28:
error: unused variable 'pkt' [-Werror=unused-variable]
     struct os_mbuf_pkthdr *pkt;
                            ^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c: At top
level:
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:331:1:
error: 'oc_ble_frag' defined but not used [-Werror=unused-function]
 oc_ble_frag(struct os_mbuf *m, uint16_t mtu)
 ^
cc1: all warnings being treated as errors

X-Original-Commit: 0087dff59b009b16ce2e57d82df2fc198f8a0997