nimble/controller: Fix build issue when BT5_PHY is set but not EXT ADV
This fixes:
Error: repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_conn.c:
In function 'ble_ll_conn_slave_start':
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_conn.c:4003:5:
error: implicit declaration of function 'ble_ll_conn_init_phy'
[-Werror=implicit-function-declaration]
     ble_ll_conn_init_phy(connsm, rxhdr->rxinfo.phy);

X-Original-Commit: f327b644af20d7a3289c723b7c8f9ed119f7a7c7