nimble/ll: Fix for compiler warning
This patch solves issue which is visible when building with -Og option.
ble_ll_conn.c:2365:18: error: 'init_addr' may be used uninitialized in this function [-Werror=maybe-uninitialized]

X-Original-Commit: ed8564d9b0a91bd1ae0fa3157f3df274eaf2bf78