Fix host unit test compiler error on mac.
This addresses the following compiler error encountered in macOS:

    Compiling net/nimble/host/test/src/ble_hs_test_util.c
    net/nimble/host/test/src/ble_hs_test_util.c: In function 'ble_hs_test_util_create_rpa_conn':
    net/nimble/host/test/src/ble_hs_test_util.c:411:79: error: macro "memcpy" passed 10 arguments, but takes just 3
         memcpy(evt2.features, (uint8_t[]){ conn_features, 0, 0, 0, 0, 0, 0, 0 }, 8);
                                                                                   ^
    net/nimble/host/test/src/ble_hs_test_util.c:411:5: error: statement with no effect [-Werror=unused-value]
         memcpy(evt2.features, (uint8_t[]){ conn_features, 0, 0, 0, 0, 0, 0, 0 }, 8);
         ^
    cc1: all warnings being treated as errors

This error occurs on the mac because its standard library implements
`memcpy()` as a macro rather than a function.  The reason for the error
is explained here: https://stackoverflow.com/a/5559334.  Basically, the
preprocessor doesn't understand the full C syntax, so arguments to
macros need special treatment.

The fix is to surround the compound literal argument with an extra set
of parenthesis.

X-Original-Commit: 0bf7a4009fe683178d8912641f02d88314ec312b