nimble/host: Rename STRINGIFY to aviod compile error
If `STRINGIFY` is also defined in the kernel or other third-party
libraries, it will cause the following error:

ble_gatts_lcl.c:95: error:"STRINGIFY" redefined [-Werror]
   95 | #define STRINGIFY(X) #X

In order to prevent this situation, rename to `NIMBLE_STRINGIFY`.

Signed-off-by: v-tangmeng <v-tangmeng@xiaomi.com>