nimble/controller: Fix controller unit test
This fix following build error due to uint32_t being defined as 'unsigned int'
instead of 'unsigned long int'
Error: repos/apache-mynewt-core/net/nimble/controller/src/ble_ll.c: In function 'ble_ll_log_dump_index':
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll.c:1391:30: error: format '%u' expects argument
    of type 'unsigned int', but argument 2 has type 'uint32_t {aka long unsigned int}' [-Werror=format=]
     console_printf("cputime=%u id=%u a8=%u a16=%u a32=%u\n",
                              ^
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll.c:1391:56: error: format '%u' expects argument
    of type 'unsigned int', but argument 6 has type 'uint32_t {aka long unsigned int}' [-Werror=format=]
     console_printf("cputime=%u id=%u a8=%u a16=%u a32=%u\n",
cc1: all warnings being treated as errors

This is just a quick workaround for now.

X-Original-Commit: 34670d729cec2d99b1408a74cb69d60364d8a867