nimble/ll: Fix build issue when BLE_LL_STRICT_CONN_SCHEDULING is set
This patch fixes that:

Error: repos/apache-mynewt-nimble/nimble/controller/src/ble_ll_conn.c: In function 'ble_ll_conn_end':
repos/apache-mynewt-nimble/nimble/controller/src/ble_ll_conn.c:1818:13: error: redeclaration of 'sr' with no linkage
     os_sr_t sr;
             ^~