porting: Add missing include in linux example
main.c: In function ‘main’:
main.c:65:33: warning: implicit declaration of function ‘atoi’ [-Wimplicit-function-declaration]
   65 |         ble_hci_sock_set_device(atoi(argv[1]));
      |                                 ^~~~